export const JWT_ENV_KEYS = [
  'JWT_SECRET',
  'JWT_EXPIRATION_TIME',
  'JWT_REFRESH_TOKEN_SECRET',
  'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  'JWT_ACTIVATE_ACCOUNT_EXPIRATION_TIME',
  'JWT_RESET_PASSWORD_EXPIRATION_TIME',
] as const;

export const DEFAULT_JWT_ENVS: Record<
  (typeof JWT_ENV_KEYS)[number],
  string | number | boolean
> = {
  JWT_SECRET: 'secret',
  JWT_EXPIRATION_TIME: '10m',
  JWT_REFRESH_TOKEN_SECRET: 'secret',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: '7d',
  JWT_ACTIVATE_ACCOUNT_EXPIRATION_TIME: '30m',
  JWT_RESET_PASSWORD_EXPIRATION_TIME: '30m',
};

export type IJwtEnvKeys = (typeof JWT_ENV_KEYS)[number];
