// Mock for @faker-js/faker to avoid ES module issues in Jest
const mockFaker = {
  internet: {
    email: jest.fn(() => 'test@example.com'),
    password: jest.fn(() => 'testpassword123'),
    url: jest.fn(() => 'https://example.com'),
    domainName: jest.fn(() => 'example.com'),
    userName: jest.fn(() => 'testuser'),
    firstName: jest.fn(() => 'John'),
    lastName: jest.fn(() => 'Doe'),
    fullName: jest.fn(() => 'John Doe'),
    ip: jest.fn(() => '192.168.1.1'),
    mac: jest.fn(() => '00:1B:44:11:3A:B7'),
    userAgent: jest.fn(
      () => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    ),
    color: jest.fn(() => '#ff0000'),
    emoji: jest.fn(() => '😀'),
    avatar: jest.fn(() => 'https://via.placeholder.com/150'),
    image: jest.fn(() => 'https://via.placeholder.com/640x480'),
    imageUrl: jest.fn(() => 'https://via.placeholder.com/640x480'),
    lorem: jest.fn(() => 'Lorem ipsum dolor sit amet'),
    word: jest.fn(() => 'test'),
    words: jest.fn(() => 'test words'),
    sentence: jest.fn(() => 'This is a test sentence.'),
    sentences: jest.fn(() => 'This is a test sentence. Another test sentence.'),
    paragraph: jest.fn(
      () => 'This is a test paragraph with multiple sentences.',
    ),
    paragraphs: jest.fn(
      () => 'This is a test paragraph. Another test paragraph.',
    ),
    text: jest.fn(() => 'Test text'),
    lines: jest.fn(() => 'Line 1\nLine 2\nLine 3'),
    slug: jest.fn(() => 'test-slug'),
    uuid: jest.fn(() => '123e4567-e89b-12d3-a456-426614174000'),
    datatype: {
      boolean: jest.fn(() => true),
      number: jest.fn(() => 42),
      float: jest.fn(() => 42.5),
      datetime: jest.fn(() => new Date()),
      string: jest.fn(() => 'test string'),
      array: jest.fn(() => ['item1', 'item2']),
      json: jest.fn(() => '{"key": "value"}'),
      hexaDecimal: jest.fn(() => '0x1A2B3C'),
      bigInt: jest.fn(() => BigInt(123)),
    },
    date: {
      past: jest.fn(() => new Date('2020-01-01')),
      future: jest.fn(() => new Date('2025-01-01')),
      recent: jest.fn(() => new Date()),
      soon: jest.fn(() => new Date()),
      between: jest.fn(() => new Date()),
      betweens: jest.fn(() => [new Date(), new Date()]),
      month: jest.fn(() => 'January'),
      weekday: jest.fn(() => 'Monday'),
      birthdate: jest.fn(() => new Date('1990-01-01')),
    },
    name: {
      firstName: jest.fn(() => 'John'),
      lastName: jest.fn(() => 'Doe'),
      fullName: jest.fn(() => 'John Doe'),
      middleName: jest.fn(() => 'Michael'),
      jobTitle: jest.fn(() => 'Software Engineer'),
      jobDescriptor: jest.fn(() => 'Senior'),
      jobArea: jest.fn(() => 'Engineering'),
      jobType: jest.fn(() => 'Developer'),
      prefix: jest.fn(() => 'Mr.'),
      suffix: jest.fn(() => 'Jr.'),
      gender: jest.fn(() => 'male'),
      sex: jest.fn(() => 'male'),
    },
    address: {
      streetAddress: jest.fn(() => '123 Main St'),
      secondaryAddress: jest.fn(() => 'Apt 4B'),
      city: jest.fn(() => 'New York'),
      state: jest.fn(() => 'NY'),
      zipCode: jest.fn(() => '10001'),
      country: jest.fn(() => 'United States'),
      countryCode: jest.fn(() => 'US'),
      latitude: jest.fn(() => 40.7128),
      longitude: jest.fn(() => -74.006),
      direction: jest.fn(() => 'North'),
      cardinalDirection: jest.fn(() => 'North'),
      ordinalDirection: jest.fn(() => 'North'),
      nearbyGPSCoordinate: jest.fn(() => [40.7128, -74.006]),
      timeZone: jest.fn(() => 'America/New_York'),
    },
    phone: {
      number: jest.fn(() => '555-123-4567'),
      phoneNumber: jest.fn(() => '555-123-4567'),
      phoneNumberFormat: jest.fn(() => '(555) 123-4567'),
      phoneFormats: jest.fn(() => '(555) 123-4567'),
      imei: jest.fn(() => '123456789012345'),
    },
    company: {
      name: jest.fn(() => 'Acme Corp'),
      companyName: jest.fn(() => 'Acme Corp'),
      companySuffix: jest.fn(() => 'Inc'),
      catchPhrase: jest.fn(() => 'Innovative solutions'),
      bs: jest.fn(() => 'revolutionary technologies'),
      buzzNoun: jest.fn(() => 'synergy'),
      buzzVerb: jest.fn(() => 'leverage'),
      buzzAdjective: jest.fn(() => 'innovative'),
      buzzPhrase: jest.fn(() => 'cutting-edge solutions'),
    },
    finance: {
      account: jest.fn(() => '1234567890'),
      accountName: jest.fn(() => 'Checking Account'),
      routingNumber: jest.fn(() => '123456789'),
      mask: jest.fn(() => '****-****-****-1234'),
      amount: jest.fn(() => 100.5),
      currency: jest.fn(() => 'USD'),
      currencyCode: jest.fn(() => 'USD'),
      currencyName: jest.fn(() => 'US Dollar'),
      currencySymbol: jest.fn(() => '$'),
      bitcoinAddress: jest.fn(() => '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa'),
      ethereumAddress: jest.fn(
        () => '0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6',
      ),
      litecoinAddress: jest.fn(() => 'LTC1qT3Sh2u567m3N6LQkzS1vFfG2r3c4w5'),
      creditCardNumber: jest.fn(() => '4532-1234-5678-9012'),
      creditCardCVV: jest.fn(() => '123'),
      creditCardIssuer: jest.fn(() => 'Visa'),
      transactionDescription: jest.fn(() => 'Payment to merchant'),
      transactionType: jest.fn(() => 'debit'),
    },
    database: {
      column: jest.fn(() => 'id'),
      type: jest.fn(() => 'varchar'),
      collation: jest.fn(() => 'utf8_general_ci'),
      engine: jest.fn(() => 'InnoDB'),
      mongodbObjectId: jest.fn(() => '507f1f77bcf86cd799439011'),
    },
    git: {
      branch: jest.fn(() => 'main'),
      commitEntry: jest.fn(() => ({
        message: 'Initial commit',
        author: 'John Doe',
        date: new Date(),
        hash: 'a1b2c3d4e5f6',
      })),
      commitMessage: jest.fn(() => 'Initial commit'),
      commitSha: jest.fn(() => 'a1b2c3d4e5f6'),
      shortSha: jest.fn(() => 'a1b2c3'),
    },
    hacker: {
      abbreviation: jest.fn(() => 'API'),
      adjective: jest.fn(() => 'cyber'),
      noun: jest.fn(() => 'protocol'),
      verb: jest.fn(() => 'hack'),
      ingverb: jest.fn(() => 'hacking'),
      phrase: jest.fn(() => 'hack the system'),
    },
    image: {
      image: jest.fn(() => 'https://via.placeholder.com/640x480'),
      imageUrl: jest.fn(() => 'https://via.placeholder.com/640x480'),
      avatar: jest.fn(() => 'https://via.placeholder.com/150'),
      imageUrl: jest.fn(() => 'https://via.placeholder.com/640x480'),
      abstract: jest.fn(() => 'https://via.placeholder.com/640x480'),
      animals: jest.fn(() => 'https://via.placeholder.com/640x480'),
      business: jest.fn(() => 'https://via.placeholder.com/640x480'),
      cats: jest.fn(() => 'https://via.placeholder.com/640x480'),
      city: jest.fn(() => 'https://via.placeholder.com/640x480'),
      food: jest.fn(() => 'https://via.placeholder.com/640x480'),
      nightlife: jest.fn(() => 'https://via.placeholder.com/640x480'),
      fashion: jest.fn(() => 'https://via.placeholder.com/640x480'),
      people: jest.fn(() => 'https://via.placeholder.com/640x480'),
      nature: jest.fn(() => 'https://via.placeholder.com/640x480'),
      sports: jest.fn(() => 'https://via.placeholder.com/640x480'),
      technics: jest.fn(() => 'https://via.placeholder.com/640x480'),
      transport: jest.fn(() => 'https://via.placeholder.com/640x480'),
      dataUri: jest.fn(
        () =>
          'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMSIgaGVpZ2h0PSIxIiB2aWV3Qm94PSIwIDAgMSAxIiBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9IiMwMDAiLz48L3N2Zz4=',
      ),
    },
    lorem: {
      word: jest.fn(() => 'test'),
      words: jest.fn(() => 'test words'),
      sentence: jest.fn(() => 'This is a test sentence.'),
      sentences: jest.fn(
        () => 'This is a test sentence. Another test sentence.',
      ),
      paragraph: jest.fn(
        () => 'This is a test paragraph with multiple sentences.',
      ),
      paragraphs: jest.fn(
        () => 'This is a test paragraph. Another test paragraph.',
      ),
      text: jest.fn(() => 'Test text'),
      lines: jest.fn(() => 'Line 1\nLine 2\nLine 3'),
      slug: jest.fn(() => 'test-slug'),
    },
    music: {
      genre: jest.fn(() => 'Rock'),
      songName: jest.fn(() => 'Test Song'),
    },
    person: {
      firstName: jest.fn(() => 'John'),
      lastName: jest.fn(() => 'Doe'),
      fullName: jest.fn(() => 'John Doe'),
      middleName: jest.fn(() => 'Michael'),
      jobTitle: jest.fn(() => 'Software Engineer'),
      jobDescriptor: jest.fn(() => 'Senior'),
      jobArea: jest.fn(() => 'Engineering'),
      jobType: jest.fn(() => 'Developer'),
      prefix: jest.fn(() => 'Mr.'),
      suffix: jest.fn(() => 'Jr.'),
      gender: jest.fn(() => 'male'),
      sex: jest.fn(() => 'male'),
      bio: jest.fn(() => 'Software engineer with 5 years of experience'),
      bioPattern: jest.fn(() => 'Software engineer with 5 years of experience'),
      zodiacSign: jest.fn(() => 'Aries'),
    },
    science: {
      chemicalElement: jest.fn(() => 'Hydrogen'),
      unit: jest.fn(() => 'meter'),
    },
    vehicle: {
      vehicle: jest.fn(() => 'Toyota Camry'),
      manufacturer: jest.fn(() => 'Toyota'),
      model: jest.fn(() => 'Camry'),
      type: jest.fn(() => 'Sedan'),
      fuel: jest.fn(() => 'Gasoline'),
      vin: jest.fn(() => '1HGBH41JXMN109186'),
      color: jest.fn(() => 'Silver'),
    },
    word: {
      adjective: jest.fn(() => 'beautiful'),
      adverb: jest.fn(() => 'quickly'),
      conjunction: jest.fn(() => 'and'),
      interjection: jest.fn(() => 'wow'),
      noun: jest.fn(() => 'house'),
      preposition: jest.fn(() => 'in'),
      verb: jest.fn(() => 'run'),
      words: jest.fn(() => ['beautiful', 'house', 'quickly']),
    },
    random: {
      alpha: jest.fn(() => 'abc'),
      alphaNumeric: jest.fn(() => 'abc123'),
      numeric: jest.fn(() => '123'),
      word: jest.fn(() => 'test'),
      words: jest.fn(() => 'test words'),
      locale: jest.fn(() => 'en'),
      uuid: jest.fn(() => '123e4567-e89b-12d3-a456-426614174000'),
      boolean: jest.fn(() => true),
      arrayElement: jest.fn(() => 'item1'),
      arrayElements: jest.fn(() => ['item1', 'item2']),
      objectElement: jest.fn(() => 'value'),
      uuid: jest.fn(() => '123e4567-e89b-12d3-a456-426614174000'),
    },
    seed: jest.fn(),
    setDefaultRefDate: jest.fn(),
    getDefaultRefDate: jest.fn(() => new Date()),
    setLocale: jest.fn(),
    getLocale: jest.fn(() => 'en'),
    locales: jest.fn(() => ['en', 'es', 'fr']),
    locale: jest.fn(() => 'en'),
    fake: jest.fn(() => 'fake data'),
    helpers: {
      arrayElement: jest.fn(() => 'item1'),
      arrayElements: jest.fn(() => ['item1', 'item2']),
      objectElement: jest.fn(() => 'value'),
      slugify: jest.fn(() => 'test-slug'),
      mustache: jest.fn(() => 'Hello {{name}}'),
      shuffle: jest.fn(() => ['item2', 'item1']),
      unique: jest.fn(() => 'unique-value'),
      replaceSymbolWithNumber: jest.fn(() => '123-456-7890'),
      replaceSymbols: jest.fn(() => 'ABC-123'),
      repeatString: jest.fn(() => 'testtesttest'),
      regexpStyleStringParse: jest.fn(() => 'test'),
      cardinal: jest.fn(() => 'one'),
      ordinal: jest.fn(() => 'first'),
      sample: jest.fn(() => 'sample'),
      weightedArrayElement: jest.fn(() => 'weighted-item'),
      arrayRange: jest.fn(() => [1, 2, 3]),
    },
  },
};

module.exports = {
  faker: mockFaker,
};
